# Site settings
# in the templates available like {{ site.myvariable }}.
#title: 
email: babydonotcry.tw@gmail.com
brand: gant.伟
headline: 旧书不厌百回读，熟读精思子自知
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.weitangx.com" # the base hostname & protocol for your site
copyright: 2019 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
#snapwidget: 247552

# Contacts
email: babydonotcry.tw@gmail.com
#phone: +1-800-555-2016

# Tracking
#googleAnalitycsID: UA-83933844-1

